# Generated by Django 4.2 on 2024-06-13 03:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("expert_name", models.CharField(max_length=255)),
                ("gpt_model", models.CharField(max_length=255)),
                (
                    "chat_history",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.JSONField(), default=list, size=None
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="SystemPrompt",
            fields=[
                ("expert_id", models.AutoField(primary_key=True, serialize=False)),
                ("expert_name", models.CharField(max_length=255, unique=True)),
                ("prompt", models.TextField()),
            ],
        ),
    ]
