# Generated by Django 4.2 on 2024-06-13 07:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="meta_data",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
