# Generated by Django 4.2 on 2024-06-13 08:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_conversation_meta_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conversation",
            name="created_at",
        ),
    ]
